### PR TITLE
MessageToolbar

### PR DESCRIPTION
**Pull request by tareksabry1337**
First library to be in this list :D

### CODE REVIEW

**Comment by Yoloabdo** [comment]
ya welcome 💃 

please add the category as a title, like in https://github.com/vsouza/awesome-ios

**Comment by tareksabry1337** [comment]
What category does this fit into ? :D

**Comment by Yoloabdo** [comment]
definitely UI : /messaging for example

**Comment by tareksabry1337** [comment]
Done.

**Comment by Yoloabdo** [comment]
Thanks

**Pull request merged**
